server:
  port: 8080
  servlet: 
    context-path: /leader
spring:
  application:
    name: leader
  profiles:
    active: dev
  jackson:
    time-zone: "GMT+8"
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  http:
    encoding:
      charset: UTF-8
      force: true
  mvc:
    pathmatch:
      # springboot2.6版本Spring MVC 处理映射匹配的默认策略已从AntPathMatcher更改为PathPatternParser
      matching-strategy: ant-path-matcher
      # springboot2.0x中，默认不支持带后缀.do，此处如果关闭*.do请求将全部失效
      use-suffix-pattern: true
# server.jsp-servlet.init-parameters.development=true # 修改JSP文件，页面动态更新，但不起作用。