#日常环境

##配置sql打印日志
spring:
  datasource:
    matrix:  # 数据源1
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 192.168.254.133 leader-mysql.com 此处需要覆盖host文件
      url: jdbc:mysql://leader-mysql.com:3306/matrix?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Hongkong
      username: root
      password: XianYue1998@
  cloud:
    nacos:
      discovery:
        server-addr: nacos-node1.pre:8848



















