apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: leader
  name: leader
  namespace: mdf-dev   # 一定要写名称空间，即k8s的namespace，KubeSphere的项目；可以区分出dev、beta、pre和prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: leader
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: leader
    spec:
      imagePullSecrets:
        - name: aliyun-docker-hub-secrets  #提前在项目下配置访问阿里云的账号密码
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/leader:snapshot-$BUILD_NUMBER
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            timeoutSeconds: 10
#            failureThreshold: 30
#            periodSeconds: 5
          imagePullPolicy: Always
          name: app
          ports:
            - name: tcp-8080               # 必须指明，否则会出现http-0的情况
              containerPort: 8080
              protocol: TCP
          resources:
            limits:                                 # 资源预留
              cpu: 2000m
              memory: 2000Mi
          terminationMessagePath: /opt/application/logs/termination-log             # 统一日志输出
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: leader
  name: leader-dev-service-np
  namespace: mdf-dev
spec:
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32603                    # 指定开放端口32603
  selector:
    app: leader
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: leader
  name: leader-dev-service-inner
  namespace: mdf-dev
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: leader
  sessionAffinity: None
  type: ClusterIP










