server:
  port: 8086
  servlet: 
    context-path: /matrix-gateway

spring:
  application:
    name: matrix-gateway
  profiles:
    active: dev
  jackson:
    time-zone: "GMT+8"
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  http:
    encoding:
      charset: UTF-8
      force: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由